#!/usr/bin/env python
import daemon
import subprocess

dir_path = '/home/root/machine2014/code/src'
spawner_path = '%s/tools/process_spawner.py'
collector_path = '%s/spawn_collector.py'
pin = 'P8_12'

with daemon.DaemonContext():
    subprocess.call([spawner_path, pin, collector_path])
